- hosts: target
  tasks:
    - name: copy artifact
      ansible.builtin.copy:
        src: main.rb
        dest: /home/vagrant/main.rb
        mode: "0777"

    - name: install ruby
      become: yes
      command: sudo yum install -y ruby.x86_64

    - name: install sinatra
      become: yes
      command: gem install sinatra -v1.4.8

