- hosts: target
  tasks:
    - name: copy artifact
      ansible.builtin.copy:
        src: main.rb
        dest: /home/vagrant/main.rb
        mode: "0777"

    - name: copy artifact
      ansible.builtin.copy:
        src: sampleruby
        dest: /home/vagrant/sampleruby
        mode: "0777"

    - name: install ruby
      become: yes
      command: sudo yum install -y ruby.x86_64

    - name: install sinatra
      become: yes
      command: gem install sinatra -v1.4.8
    
    - name: create simple service template
      become: true
      template:
        src: sampleruby.service.j2
        dest: /etc/systemd/system/sampleruby.service

    - name: run sampleruby service
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: sampleruby
        enabled: yes

